### ISSUE TITLE
Nothing shows...

### ISSUE THREAD

**Issue by jartantupjar** [OpenATK/TrialsTracker#1]
Hello again...
after checking back a few months later i attempted to try once again but this time nothing shows in the localhost 8000 and i think its because i got lost in the instructions : demo=TrialsTracker npm start
![capture](https://cloud.githubusercontent.com/assets/19889070/18610338/4502767c-7d4c-11e6-94eb-7678ee8f59dd.JPG)

**Comment by aultac** [comment]
@jartantupjar Looks like our devDependencies are missing a few things (webpack, babel-core, babel-preset-es2015, and babel-loader).  I've updated them.  Please pull again, `npm install` again, and see how it goes.

**Comment by jartantupjar** [comment]
Okay now it finally worked. Can you add in the readme file that one needs to npm install express before one can make it work. Thank you

**Comment by aultac** [comment]
Thanks! That needed to be added to package.json too, so I pushed it up to dev and master branches.
